namespace Project_Assets.Scripts.Enums
{
    public enum UnitType
    {
        ManAlchemistA,
        ManAlchemistB,
        ManAlchemistC,
        ManBlacksmithA,
        ManSoldierFullPlateFantasyA,
        ManSoldierFullPlateFantasyAOpen,
        ManSoldierFullPlateFantasyB,
        ManSoldierFullPlateFantasyC,
        ManSoldierHoundSkullA,
        ManSoldierHoundSkullAOpen,
        ManSoldierHoundSkullB,
        ManSoldierHoundSkullBOpen,
        ManSoldierHoundSkullC,
        ManSoldierHoundSkullCOpen,
        ManSoldierRangerFantasyA,
        ManSoldierRangerFantasyB,
        ManSoldierRangerFantasyC,
        ManVillagerA,
        ManVillagerB,
        ManVillagerC,
        WomanHeadbandFantasy,
        WomanHeadscarfFantasy,
        WomanPrincessDressNarrowFantasy,
        WomanPrincessDressWideFantasy,
        WomanSoldierFullPlateFantasy,
    }
}